import React from 'react';
import { X, FileText } from 'lucide-react';
import { APP_NAME, DOMAIN, CONTACT_EMAIL } from '../config';

interface TermsModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const TermsModal: React.FC<TermsModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-md animate-fadeIn">
      <div className="relative w-full max-w-2xl bg-slate-900 border border-slate-700 rounded-3xl p-6 sm:p-8 text-slate-300 shadow-2xl flex flex-col gap-4 max-h-[85vh] overflow-y-auto">
        <div className="flex items-center justify-between pb-3 border-b border-slate-800">
          <div className="flex items-center gap-2 text-white">
            <FileText className="w-5 h-5 text-indigo-400" />
            <h2 className="text-xl font-bold tracking-tight">Terms of Service</h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-full hover:bg-slate-800 text-slate-400 hover:text-white transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="space-y-4 text-xs sm:text-sm leading-relaxed">
          <p className="text-slate-400">
            Last updated: October 2026. By accessing {APP_NAME} ({DOMAIN}), you agree to these Terms.
          </p>

          <h3 className="text-sm sm:text-base font-bold text-white pt-2">1. Eligibility</h3>
          <p>
            You must be at least 13 years of age to use {APP_NAME}.
          </p>

          <h3 className="text-sm sm:text-base font-bold text-white pt-2">2. Content Ownership and Rights</h3>
          <p>
            You retain full ownership and intellectual property rights in any images or videos you import and export through the tool. You represent and warrant that you own or have obtained all necessary licenses, permissions, and rights to use and publish any photos you process.
          </p>

          <h3 className="text-sm sm:text-base font-bold text-white pt-2">3. Acceptable Use</h3>
          <p>
            You agree not to use {APP_NAME} to generate content that involves harassment, defamation, deceptive malicious impersonation, hateful discrimination, or any sexually explicit or abusive material involving minors.
          </p>

          <h3 className="text-sm sm:text-base font-bold text-white pt-2">4. Promotional Frame</h3>
          <p>
            Standard free video and image exports generated by {APP_NAME} include a styled branding border ("Made with {APP_NAME}"). Tampering with or altering exports to misrepresent authorship is not permitted under the free tier.
          </p>

          <h3 className="text-sm sm:text-base font-bold text-white pt-2">5. Disclaimer of Warranties</h3>
          <p>
            {APP_NAME} is provided "as is" without warranty of any kind. As a purely client-side static application, availability and export capabilities depend upon your device's browser and hardware capabilities.
          </p>

          <h3 className="text-sm sm:text-base font-bold text-white pt-2">6. Takedown & Inquiries</h3>
          <p>
            Because media is not hosted on our servers, we cannot remove content published to third-party social networks. For copyright inquiries or legal questions, reach out to{' '}
            <a href={`mailto:${CONTACT_EMAIL}`} className="text-indigo-400 underline">
              {CONTACT_EMAIL}
            </a>.
          </p>
        </div>
      </div>
    </div>
  );
};
